[tool.poetry]
name = "black-mamba"
version = "0.3.5"
description = "Development framework to write, test and deploy smart contracts written in Vyper. It has integrated web3.py support."
authors = ["Arjuna Sky Kok <arjuna@mamba.black>"]
license = "LGPL-3.0"
readme = "README.md"
repository = "https://github.com/arjunaskykok/mamba"
homepage = "https://mamba.black"
keywords = ["blockchain"]
classifiers = [
  "Topic :: Software Development :: Build Tools",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.6"
vyper = "0.1.0b17"
pytest = "5.4.1"
web3 = "5.9.0"
eth-tester = "0.4.0b1"
py-evm = "0.3.0a14"

[tool.poetry.scripts]
mamba = "black_mamba.mamba_cli:parse_cli_args"
